<?php
return [
    'DB_HOST' => 'localhost',
    'DB_NAME' => 'aed_crm',
    'DB_USER' => 'root',
    'DB_PASS' => '',
    'APP_URL' => 'http://localhost/MUEBES_SAN_MARTIN_GESTOR/',
    'GOOGLE_MAPS_API_KEY' => 'AIzaSyCY24rP5kEv4iuBK6u7gtItI3Q3hWhjWBg',
    'GEMINI_API_KEY' => 'AQ.Ab8RN6La52XOBoRy2qwsu3xhvznMD7U9_NjqpoGHkNX85imt-w',
    'GEMINI_MODEL' => 'gemini-3.5-flash',
    'APP_NAME' => 'Mueblería San Martínes',
    'BUSINESS_LOGO' => 'storage/assets/logo_6a2ae31211305.png',
    'THEME_SIDEBAR_BG' => '#f5f5f5',
    'THEME_PRIMARY' => '#9c67fe',
    'seo_titulo' => ' hola',
    'THEME_SIDEBAR_TEXT' => '#454545',
    'THEME_TEXT_COLOR' => '#374151',
    'THEME_TOPBAR_BG' => '#ffffff',
    'THEME_BODY_BG' => '#f3f4f6',
];
