-- 1. Crear las categorías base si no existen
INSERT IGNORE INTO `help_categorias` (`id`, `nombre`, `estado`) VALUES
(1, 'Manual del Usuario (CRM)', 'activo'),
(2, 'Políticas de Empresa', 'activo');

-- 2. Insertar los artículos del manual vinculados a la categoría 1
INSERT INTO `help_articulos` (`categoria_id`, `titulo`, `contenido`, `tipo`, `estado`) VALUES
(1, '¿Cómo registrar un nuevo cliente?', 'Para registrar un nuevo cliente, dirígete al módulo **Clientes** en el menú lateral y haz clic en el botón "Nuevo Cliente".\n\nDebes llenar al menos el nombre completo. Si el cliente se comunicó por WhatsApp, puedes vincular su número en la opción "Vincular con Chat de WhatsApp" para ver su perfil directamente cuando estés chateando con él.', 'interno', 'activo'),
(1, '¿Cómo crear una venta o cotización en el POS?', 'Ve al módulo **POS (Punto de Venta)**.\n\n1. Selecciona al cliente desde la lista desplegable (o déjalo en Público en General).\n2. Busca los productos por nombre o SKU y haz clic en ellos para agregarlos al carrito.\n3. Si la venta requiere envío, selecciona la tarifa o usa el mapa para calcular la distancia y el costo.\n4. Si el cliente va a dejar un anticipo o pago completo, anótalo en la casilla de "Recibido Hoy".\n5. Haz clic en **Confirmar Venta** (descuenta inventario) o **Guardar Cotización** (no afecta inventario).', 'interno', 'activo'),
(1, '¿Cómo gestionar las entregas y envíos?', 'Las ventas que incluyen un costo de envío o una dirección personalizada se van directamente al módulo de **Logística**.\n\nEn la pestaña "Tablero de Entregas" verás tres columnas: **Pendientes**, **En Ruta** y **Entregados**. \nSolo tienes que arrastrar las tarjetas de un lado a otro conforme avanza el proceso de entrega. Al marcar un pedido como "Entregado", el sistema registrará la fecha y hora exacta.', 'interno', 'activo'),
(1, '¿Cómo usar el Copiloto IA interno?', 'El Copiloto IA (el robot en la esquina inferior derecha) es tu asistente personal. Puedes preguntarle cosas sobre el sistema, pedirle que te redacte mensajes para clientes, o incluso consultar información de los módulos.\n\nPrueba preguntándole:\n- *"¿Cómo nos fue en las ventas de hoy?"*\n- *"¿Cuáles son las políticas de devolución?"*\n- *"Redacta un mensaje amable cobrando un saldo vencido a un cliente."*', 'interno', 'activo'),
(1, '¿Cómo registrar abonos de clientes que deben dinero?', 'Ve al módulo de **Finanzas** y haz clic en el botón "Cuentas por Cobrar".\n\nAhí verás la lista de todas las notas que tienen un saldo deudor (crédito o apartado). Haz clic en el botón verde **Abono**, ingresa la cantidad que el cliente está pagando en ese momento y elige en qué caja o cuenta bancaria entrará el dinero. El saldo restante de la nota se actualizará y la deuda bajará automáticamente.', 'interno', 'activo'),
(1, '¿Cómo conectar mi número a WhatsApp Gateway?', '1. Ve al módulo **WhatsApp Gateway**.\n2. Haz clic en el botón "Vincular / Código QR".\n3. Abre WhatsApp en tu celular, ve a "Dispositivos Vinculados" y escanea el código QR que aparece en la pantalla del CRM.\n4. Una vez conectado, podrás enviar, recibir y usar el bot de IA para contestar a tus clientes automáticamente.', 'interno', 'activo');